### ISSUE TITLE
Using KMS for contract interaction

### ISSUE THREAD

**Issue by Ryce** [aws-samples/aws-kms-ethereum-accounts#1]
Greetings,

Thanks for providing this tutorial for sending the native token from the KMS managed wallet.

However, I am facing some issues with the wallet that we have because we want to do a different kind of transaction

I have been looking for an answer to this but have not yet been lucky enough. Is there a way to construct a raw contract interaction?

best regards

**Comment by dpdornseifer** [comment]
Hi @Ryce,

the current implementation can relatively easy be extended to cover smart contract interaction as well. 
The `tx_params` dict needs to be extended with a `data` field. This `data` field then needs to carry the encoded smart contract call which has to be passed via the external signing request.

```python
 tx_params = get_tx_params(dst_address=dst_address,
                                  amount=amount,
                                  data=data
                                  nonce=nonce,
                                  chainid=chainid,
                                  type=type,
                                  max_fee_per_gas=max_fee_per_gas,
                                  max_priority_fee_per_gas=max_priority_fee_per_gas)
```
