### ISSUE TITLE
Incorrect `v` value used in eth_client_eip1559 example

### ISSUE THREAD

**Issue by ryanc-bs** [aws-samples/aws-kms-ethereum-accounts#14]
I'm trying to understand the EIP1559 example and it seems to me that the wrong value for the recovery parameter v is used.

Here we find the correct value for v, but return instead the parity value in {0, 1}: https://github.com/aws-samples/aws-kms-ethereum-accounts/blob/1c11d368fd1e00f08d744acc07bbddf5a0ed5e45/aws_kms_lambda_ethereum/_lambda/functions/eth_client_eip1559/lambda_helper.py#L148

This parity value is passed directly on to `encode_transaction` here: https://github.com/aws-samples/aws-kms-ethereum-accounts/blob/1c11d368fd1e00f08d744acc07bbddf5a0ed5e45/aws_kms_lambda_ethereum/_lambda/functions/eth_client_eip1559/lambda_helper.py#L183-L184 - I don't think this is correct, as the v value in the range {chainid * 2 + 35, chainid * 2 + 36} is expected here.

In contrast, for the `eth_client` example, the v value in the range {27, 28} is returned and is passed on to the `encode_transaction` call https://github.com/aws-samples/aws-kms-ethereum-accounts/blob/1c11d368fd1e00f08d744acc07bbddf5a0ed5e45/aws_kms_lambda_ethereum/_lambda/functions/eth_client/lambda_helper.py#L143 - this seems correct to me.

I just want to check if I have understood correctly, and if so I'm happy to raise a PR to fix.

**Comment by dpdornseifer** [comment]
Hey @ryanc-bs , 
thanks for reaching out. 

Think you are mixing up the different ways of `v` calculations for `legacy` and `EIP155` transactions. Please have a look here for a detailed explanation on this topic: https://aws.amazon.com/blogs/database/how-to-sign-ethereum-eip-1559-transactions-using-aws-kms/

The legacy tx code is located here: https://github.com/aws-samples/aws-kms-ethereum-accounts/blob/main/aws_kms_lambda_ethereum/_lambda/functions/eth_client/lambda_helper.py#L137-L145

I hope this answers your question.

**Comment by ryanc-bs** [comment]
Hi @dpdornseifer, thanks for your reply.

I guess I'm a bit confused because from the EIP-155 standard linked to from the article you shared, it does not mention using the parity value in place of the v signature parameter - it says:

> If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process.

When I use the `v` value as defined above I am able to recover the signing address from the serialized transaction using the Account.recover_transaction() method (https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.account.Account.recover_transaction) - however if I use the parity bit instead I cannot recover the original signing address, which leads me to think that using the parity bit is not correct. Could you clarify this for me?

**Comment by dpdornseifer** [comment]
@ryanc-bs,

no problem. Did you try the EIP1559 implementation with the following json request?

**Return KMS address**:
```
{
  "operation": "status"
}
```

**Sign TX with KMS"":
```
{
  "operation": "sign",
  "amount": 0.01,
  "dst_address": "0xa5D3241A1591061F2a4bB69CA0215F66520E67cf",
  "nonce": 0,
  "type": 2,
  "chainid": 4,
  "max_fee_per_gas": 100000000000,
  "max_priority_fee_per_gas": 3000000000
}
```

Recover public address via `eth_account`:
```
Account.recover_transaction("0x02f8[...]")
```

or use online transaction decode: https://toolkit.abdk.consulting/ethereum#transaction,rlp,address-checksum,key-to-address,recover-address.

**Comment by dpdornseifer** [comment]
Sry, not sure if I understand your question. You are saying that you can recover the public address via `recover_transaction` but it does not work with `v` as defined in the EIP1559 doc?

**Comment by ryanc-bs** [comment]
I think the confusion has come from the different signing mechanisms defined in EIP-155 vs EIP-1559 -  the text I quoted above comes from the EIP-155 doc.

I see that the EIP-1559 doc mentions using the y_parity value instead of the v value for signatures - so yes I think that using a parity bit in {0, 1} should be correct according to that standard. It's not clear to me why the Account.recover_transaction() method doesn't seem to support EIP-1559 transaction signatures, but that is a separate issue.
