### ISSUE TITLE
No module named cytoolz.itertoolz not found

### ISSUE THREAD

**Issue by atitawat-pol** [aws-samples/aws-kms-ethereum-accounts#4]
I followed this documentation (I skipped the part1 because I think I don't want to create the environment).
[eth-kms](https://aws.amazon.com/blogs/database/part2-use-aws-kms-to-securely-manage-ethereum-accounts/
)

Unfortunately, there is some error returned from AWS Lambda.
```
Response
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'cytoolz.itertoolz'",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "1a346678-4138-4281-9b68-3020f6da29cb",
  "stackTrace": []
}
```

I found that inside the cytoolz package, there is no itertoolz.py which caused this error from AWS Lambda.

**Comment by dpdornseifer** [comment]
Hello @atitawat-pol,

can you please elaborate on how you deployed the stack and what operation you triggered on the Lambda function that caused the issue above? Just redeployed the stack and tested both operations (status, sign) without any error.

Cheers
