### ISSUE TITLE
from aws_cdk import core ModuleNotFoundError: No module named 'aws_cdk'

### ISSUE THREAD

**Issue by albert-vo-crypto** [aws-samples/aws-kms-ethereum-accounts#5]
Followed steps in the AWS Blog:  https://aws.amazon.com/blogs/database/part1-use-aws-kms-to-securely-manage-ethereum-accounts/
but ran into following error, when running 'cdk deploy'

from aws_cdk import core ModuleNotFoundError: No module named 'aws_cdk'

**Comment by dpdornseifer** [comment]
Hi @albert-vo-crypto , 

that error indicates that the aws_cdk sources are not available in your current Python environment. Can you please execute the `pip install -r requirements.txt` step again and make sure that your current Python environment is activated ([Activating the virtualenv](https://cdkworkshop.com/30-python/20-create-project/200-virtualenv.html).
